#!/bin/bash

# Beware: this is a draft and not yet tested. Use this as datasource_program
# for a host that is an DELL iDrac remote management interface.

PATH="$PATH:/usr/sbin"
# set -x
HOST=$1
USERNAME=$2
PASSWORD=$3

# CRIT - Agent exited with code 1: SDR Cache /var/lib/nagios/.freeipmi/sdr-cache/ out of date: Please flush the cache and regenerate it
find /var/lib/nagios/.freeipmi/sdr-cache -type f -delete

echo '<<<check_mk>>>'
echo 'Version: ipmi 1.0'
echo 'AgentOS: IPMI'

if which ipmi-sensors >/dev/null 2>&1
then
    echo '<<<ipmi_sensors>>>'
    ipmi-sensors -h $1 -u $2 -p $3 -l USER -Q --session-timeout 40000 --ignore-not-available-sensors --legacy-output -D LAN_2_0 \
        | sed -e 's/ /_/g' -e 's/:_\?/ /g' -e 's@ \([^(]*\)_(\([^)]*\))@ \2_\1@' \
        | grep -vP '(Power_Unit_VRM|Health_LED|OEM_Reserved_UID_Light|Fan_Fan_|Current_Power_Meter)'
    test ${PIPESTATUS[0]} -eq 0
else
    echo '<<<ipmi>>>'
    ipmitool -i lan -H "$HOST" -U "$USERNAME" -f "$PASSWORD" sensor show 2>/dev/null \
       | grep -v 'command failed' \
       | sed -e 's/ *| */|/g' -e 's/ /_/g' -e 's/_*"'$'"//' -e 's/|/ /g' \
       | egrep -v '^[^ ]+ na ' \
       | grep -v ' discrete '
fi
