#!/usr/bin/env python
# encoding: utf-8
# @author Robin Schneider <robin.schneider@hamcos.de>
# @company hamcos IT Service GmbH http://www.hamcos.de
# @license GPLv2 <https://www.gnu.org/licenses/gpl-2.0.html>
#
# Deprecated: Use https://github.com/ypid-bot/check_mk/blob/master/agents/special/agent_netapp

"""
Nagios/Icinga check for the snapshot age of a NetApp storage system.
Additionally, this check can also fed the number of snapshots per volume as
passive check into the core.
"""

__version__ = '0.8'

# modules {{{
# std {{{
import sys
import logging
from time import time
from datetime import datetime
# }}}

from xml.sax.saxutils import escape
from NaServer import NaServer, NaElement
# }}}


def get_human_readable_date(unix_time):
    return datetime.fromtimestamp(unix_time).strftime('%Y-%m-%d %H:%M:%S')


def get_human_readable_volume_info(volume_name, volume_info):
    return "{} with oldest snapshot: {} ({})".format(
        volume_name,
        volume_info[volume_name]['oldest']['snapshot_name'],
        get_human_readable_date(
            volume_info[volume_name]['oldest']['access_time']
        ),
    )


def check_netapp_snapshot_age(
        na_server,
        max_age_days,
        max_records=500,
        abort_after=None,
        ):

    status_detail = "UNKNOWN - "
    exit_status = 3

    volume_info = dict()
    volumes_old_snapshot = set()
    volumes_ok = set()

    cur_time = int(time())

    next_tag = False

    # http://community.netapp.com/t5/Software-Development-Kit-SDK-and-API-Discussions/volume-get-iter-iteration-tag-not-working-as-expected/m-p/102384/highlight/true#M1425
    # while next_tag is not None:
    #    next_tag = escape(next_tag)
    #    if api.child_get("tag") is None:
    #       api.child_add_string("tag", next_tag)
    #    else:
    #       api.child_get("tag").set_content(next_tag)
    #    output = na_server.invoke_elem(api)
    #    print "OUTPUT:\n%s\n\n" % (output.sprintf())
    #    next_tag = output.child_get_string("next-tag")

    query = NaElement('snapshot-get-iter')
    query.child_add_string('max-records', max_records)
    # query.child_add_string('desired-attributes', NaElement('name', ''))

    total_snapshot_count = 0
    while next_tag is not None:

        if next_tag:
            logging.info('next-tag')
            next_tag = escape(next_tag)
            if query.child_get('tag') is None:
                query.child_add_string('tag', next_tag)
            else:
                query.child_get('tag').set_content(next_tag)

        # logging.info(query.sprintf())
        na_answer = na_server.invoke_elem(query)

        if na_answer.results_errno() != 0:
            status_detail += str(na_answer.results_reason())
        else:

            logging.debug(na_answer.sprintf())

            elements = na_answer.child_get('attributes-list')
            for element in elements.children_get():
                snapshot_name = element.child_get_string('name')
                volume_name = element.child_get_string('volume')
                access_time = int(element.child_get_string('access-time'))
                total_snapshot_count += 1
                if volume_name in volume_info:
                    volume_info[volume_name]['names'].append(snapshot_name)
                    if access_time < volume_info[volume_name]['oldest']['access_time']:
                        volume_info[volume_name]['oldest'] = {
                            'snapshot_name': snapshot_name,
                            'access_time': access_time,
                        }
                else:
                    volume_info[volume_name] = {
                        'names': [ snapshot_name ],
                        'oldest': {
                            'snapshot_name': snapshot_name,
                            'access_time': access_time,
                        },
                    }
                logging.info(u'{}: {} ({})'.format(
                    volume_name,
                    snapshot_name,
                    get_human_readable_date(access_time),
                ))
                if (cur_time - max_age_days*24*60*60) < access_time:
                    volumes_ok.add(volume_name)
                else:
                    volumes_old_snapshot.add(volume_name)

            next_tag = na_answer.child_get_string('next-tag')

            if abort_after is not None and total_snapshot_count >= abort_after:
                break

    if len(volumes_old_snapshot) != 0:
        exit_status = 1
        status_detail = "WARN - Snapshots older than {} days: {}".format(
            max_age_days,
            ',\\n'.join(map(
                lambda volume_name: get_human_readable_volume_info(volume_name, volume_info),
                volumes_old_snapshot,
            )),
        )
    elif len(volumes_ok) != 0:
        status_detail = "OK - Snapshots are not older than {} days: {}".format(
            max_age_days,
            ',\\n'.join(map(
                lambda volume_name: get_human_readable_volume_info(volume_name, volume_info),
                volumes_ok,
            )),
        )
        exit_status = 0
    logging.debug(u"volumes_ok: " + unicode(volumes_ok))

    return {
        'exit_status': exit_status,
        'status_detail': status_detail,
        'volume_info': volume_info,
    }


# main {{{
if __name__ == '__main__':

    from argparse import ArgumentParser

    args_parser = ArgumentParser(
        description=__doc__,
    )
    args_parser.add_argument(
        '-V', '--version',
        action='version',
        version='%(prog)s {version}'.format(version=__version__)
    )
    args_parser.add_argument(
        '-d', '--debug',
        help="Print lots of debugging statements",
        action="store_const", dest="loglevel", const=logging.DEBUG,
        default=logging.WARNING,
    )
    args_parser.add_argument(
        '-v', '--verbose',
        help="Be verbose",
        action="store_const", dest="loglevel", const=logging.INFO,
    )
    args_parser.add_argument(
        'hostname',
    )
    args_parser.add_argument(
        'user',
    )
    args_parser.add_argument(
        'password',
    )
    args_parser.add_argument(
        '-m', '--max-age-days',
        help="Maximum age of a snapshot."
        " If the snapshot is older then the value specified, a warning will be produced."
        " Default: %(default)s",
        default=1,
        type=int,
    )
    args_parser.add_argument(
        '-c', '--command-file',
        help="Command file/socket of the core."
        " Used to fed passive checks into the core."
        " Default: %(default)s",
        default='/var/lib/icinga/rw/icinga.cmd',
        type=unicode,
    )
    args_parser.add_argument(
        '-W', '--warn-num-snapshots',
        help="Warn if more then the given number of snapshots exist."
        " Default: %(default)s",
        default=240,
        type=int,
    )
    args_parser.add_argument(
        '-C', '--critical-num-snapshots',
        help="Critical event if more then the given number of snapshots exist."
        " Default: %(default)s",
        default=250,
        type=int,
    )
    args_parser.add_argument(
        '-n', '--snapshot-count-service',
        help="Service description of the passively fed snapshot count service."
        " This feature is only active if a name was given."
        " Default: %(default)s",
        type=unicode,
    )
    args_parser.add_argument(
        '-r', '--max-records',
        help="Maximum number of snapshots to request from the Filer."
        " If this number is to low, you might miss snapshots."
        " Note that the tested NetApp did not return more than 1000 entries at at time even if asked for more."
        " Default: %(default)s",
        default=500,
        type=int,
    )
    args_parser.add_argument(
        '-a', '--abort-after',
        help="Stop querying for more entry after the given number of entries has been reached."
        " Useful during development."
        " Default: %(default)s",
        default=None,
        type=int,
    )
    args = args_parser.parse_args()
    logger = logging.getLogger(__file__)
    logging.basicConfig(
        format='%(levelname)s: %(message)s',
        level=args.loglevel,
    )

    na_server = NaServer(args.hostname, 1, 1)
    na_server.set_server_type('Filer')
    na_server.set_admin_user(args.user, args.password)
    na_server.set_transport_type('HTTPS')

    result = check_netapp_snapshot_age(
        na_server,
        args.max_age_days,
        max_records=args.max_records,
        abort_after=args.abort_after,
    )

    if args.snapshot_count_service:
        warn = args.warn_num_snapshots
        critical = args.critical_num_snapshots

        critical_snapshot_count = []
        warn_snapshot_count = []
        ok_snapshot_count = []

        for volume_name, volume_item in result['volume_info'].iteritems():
            snapshot_count = len(volume_item['names'])
            if args.critical_num_snapshots and  snapshot_count > critical:
                critical_snapshot_count.append('{} has {} snapshots'.format( volume_name, snapshot_count))
            elif args.warn_num_snapshots and snapshot_count > warn:
                warn_snapshot_count.append('{} has {} snapshots'.format( volume_name, snapshot_count))
            else:
                ok_snapshot_count.append('{} has {} snapshots'.format( volume_name, snapshot_count))

        status_detail = "UNKNOWN - "
        exit_status = 3
        if len(critical_snapshot_count) != 0:
            exit_status = 2
            status_detail = "CRIT - The following volumes have too many snapshots: {}".format(
                ',\\n'.join(critical_snapshot_count),
            )
        elif len(warn_snapshot_count) != 0:
            exit_status = 1
            status_detail = "WARN - The following volumes have too many snapshots: {}".format(
                ',\\n'.join(warn_snapshot_count),
            )
        elif len(ok_snapshot_count) != 0:
            exit_status = 0
            status_detail = "OK - The number of snapshots per volume is OK for all volumes: {}".format(
                ',\\n'.join(ok_snapshot_count),
            )

        count_file = open(args.command_file, 'a')
        count_file.write(
            '[{}] PROCESS_SERVICE_CHECK_RESULT;{};{};{};{}\n'.format(
                int(time()),
                args.hostname,
                args.snapshot_count_service,
                exit_status,
                status_detail,
            )
        )
        count_file.close()

        logging.info(status_detail)

    print(result['status_detail'])
    logging.info("Snapshot count is {}.".format(result['volume_info']))
    sys.exit(result['exit_status'])

# }}}
