#!/usr/bin/env python
# encoding: utf-8
# @author Robin Schneider <robin.schneider@hamcos.de>
# @company hamcos IT Service GmbH http://www.hamcos.de
# @license GPLv2 <https://www.gnu.org/licenses/gpl-2.0.html>

import sys
from common import *
# sys.path.append("/usr/local/lib/python/NetApp/")
from NaServer import *

args = len(sys.argv) - 1
if (args < 3):
    print_usage()

filer    = sys.argv[1]
user     = sys.argv[2]
password = sys.argv[3]

s = NaServer(filer, 1, 1)
s.set_server_type('Filer')
s.set_admin_user(user, password)
s.set_transport_type('HTTPS')

status_detail = 'UNKNOWN - '
exit_status = 3

## max-records: The default is 2000 for clustered ONTAP.
output = s.invoke('storage-disk-get-iter')

if output.results_errno() != 0:
    status_detail += str(output.results_reason())
else:

    # print(output.sprintf())
    zeroed = dict()
    not_zeroed = dict()

    output = output.child_get('attributes-list')
    for i in output.children_get():
        disk_name = i.child_get_string('disk-name')
        disk_info = i.child_get('disk-raid-info')
        spare_pool = disk_info.child_get_string('spare-pool')
        disk_spare_info = disk_info.child_get('disk-spare-info')
        if disk_spare_info:
            zeroed_bool_string = disk_spare_info.child_get_string('is-zeroed')
            if zeroed_bool_string == 'true':
                if spare_pool not in zeroed.keys():
                    zeroed[spare_pool] = []
                zeroed[spare_pool].append(disk_name)
            else:
                if spare_pool not in not_zeroed.keys():
                    not_zeroed[spare_pool] = []
                not_zeroed[spare_pool].append(disk_name)
    if len(not_zeroed) != 0:
       exit_status = 1
       status_detail = "WARN - not zeroed: {}".format(not_zeroed)
    elif len(zeroed) != 0:
       status_detail = "OK - zeroed: {}".format(zeroed)
       exit_status = 0
    else:
       status_detail += "No disks in a spare group found."

print status_detail
sys.exit(exit_status)
